# Generated by Django 5.0 on 2023-12-29 00:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('idAdministrador', models.AutoField(primary_key=True, serialize=False)),
                ('nombreAdministrador', models.CharField(max_length=25)),
                ('apellidoAdministrador', models.CharField(max_length=45)),
                ('contraseniaAdministrador', models.CharField(max_length=8, unique=True)),
                ('emailAdministrador', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'Administrador',
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('idComprador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('contrasenia', models.CharField(max_length=8, unique=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Comprador',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChatConsulta',
            fields=[
                ('idChatConsulta', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCreada', models.DateField(auto_now_add=True)),
                ('kfComprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMiTienda.comprador')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'db_table': 'ChatConsulta',
            },
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('idConsulta', models.AutoField(primary_key=True, serialize=False)),
                ('fechaHoraEnviado', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.CharField(max_length=500)),
                ('kfChatConsulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMiTienda.chatconsulta')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=25)),
                ('descripcionProducto', models.CharField(max_length=255)),
                ('costoProducto', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('precioProducto', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('stockProducto', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('imagenProducto', models.ImageField(upload_to='imagenes/')),
                ('fechaIngreso', models.DateField(auto_now_add=True)),
                ('fechaActualizacion', models.DateField(auto_now=True)),
                ('kfCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMiTienda.categorias')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idCarrito', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadProducto', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('kfComprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMiTienda.comprador')),
                ('kfProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMiTienda.productos')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
                'db_table': 'Carrito',
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('idRecibo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaHoraEmitida', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('estadoPedido', models.CharField(choices=[('PRE', 'Preparar'), ('PRO', 'Procesado'), ('ENV', 'Enviado'), ('ENT', 'Entregado'), ('CAN', 'Cancelado')], default='PRE', max_length=3)),
                ('kfComprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMiTienda.comprador')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'db_table': 'Recibo',
            },
        ),
        migrations.CreateModel(
            name='DetalleRecibo',
            fields=[
                ('idDetalleRecibo', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=45)),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('precioUnitario', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('kfRecibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMiTienda.recibo')),
            ],
            options={
                'verbose_name': 'Detalle de Recibo',
                'verbose_name_plural': 'Detalles de Recibo',
                'db_table': 'DetalleRecibo',
            },
        ),
        migrations.CreateModel(
            name='DetalleEnvio',
            fields=[
                ('idDetalleEnvio', models.AutoField(primary_key=True, serialize=False)),
                ('fechaEnvio', models.DateField()),
                ('direccionEnvio', models.CharField(max_length=100)),
                ('detalleEntrega', models.CharField(blank=True, max_length=300, null=True)),
                ('kfRecibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMiTienda.recibo')),
            ],
            options={
                'verbose_name': 'Detalle de envío',
                'db_table': 'DetalleEnvio',
            },
        ),
        migrations.CreateModel(
            name='ValoracionProducto',
            fields=[
                ('idValoracionProducto', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(blank=True, max_length=300, null=True)),
                ('calificacion', models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=5)])),
                ('fechaCalificacion', models.DateField(auto_now_add=True)),
                ('kfComprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMiTienda.comprador')),
                ('kfProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMiTienda.productos')),
            ],
            options={
                'verbose_name': 'Valoración',
                'verbose_name_plural': 'Valoraciones',
                'db_table': 'ValoracionProducto',
            },
        ),
    ]
